version: "3"
services:
  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  rolldice-app:
    image: rolldice
    build:
      context: ./
    container_name: rolldice-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - OTEL_SERVICE_NAME=rolldice_app
    networks:
      - rolldice-app-network
    depends_on:
      - tempo
      # - jaeger
      - otel-collector
    # I don't think adding this to the rolldice-app-network is necessary

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   container_name: jaeger
  #   environment:
  #     - COLLECTOR_ZIPKIN_HOST_PORT=:9411
  #   ports:
  #     - "16686:16686"
  #     - "9411:9411"
  #   networks:
  #     - rolldice-app-network

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "3200:3200"
    networks:
      - rolldice-app-network
    depends_on:
      - init
  
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
    networks:
      - rolldice-app-network
    depends_on:
      - tempo
      # - jaeger # (if using)

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - rolldice-app-network

  grafana:
    container_name: grafana
    image: grafana/grafana:11.2.0
    volumes:
      - ./shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app
    networks:
      - rolldice-app-network
    depends_on:
      - tempo
    
networks:
  rolldice-app-network:
    name: rolldice-app-network